services:
  # EntroSpies Telegram Bot Service
  entrospies-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: entrospies-bot
    restart: unless-stopped
    
    # Environment variables from .env file
    env_file:
      - .env
    
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      - PYTHONPATH=/app
    
    # Volume mounts for persistent data
    volumes:

      # Persistent data directories (read-write)
      - ./telegram_bots/download:/app/telegram_bots/download
      - ./telegram_bots/logs:/app/telegram_bots/logs
      - ./telegram_bots/session:/app/telegram_bots/session
      
      # Code directories (read-only for security)
      - ./telegram_bots/infostealer_parser:/app/telegram_bots/infostealer_parser:ro
      - ./telegram_bots/scripts:/app/telegram_bots/scripts:ro
      - ./telegram_bots/config:/app/telegram_bots/config:ro
      - ./telegram_bots/elasticsearch:/app/telegram_bots/elasticsearch:ro
      
      # Bot files (read-only)
      - ./telegram_bots/infostealer_bot.py:/app/telegram_bots/infostealer_bot.py:ro
      - ./telegram_bots/logger.py:/app/telegram_bots/logger.py:ro
      - ./telegram_bots/telethon_download_manager.py:/app/telegram_bots/telethon_download_manager.py:ro
      - ./telegram_bots/archive_decompressor.py:/app/telegram_bots/archive_decompressor.py:ro
      - ./telegram_bots/master_workflow_orchestrator.py:/app/telegram_bots/master_workflow_orchestrator.py:ro
    
    # Network configuration
    networks:
      - entrospies-network
    
    # Health check
    healthcheck:
      test: ["CMD", "python3", "-c", "import os; import sys; sys.exit(0 if os.path.exists('/app/telegram_bots/logs/message_collector.log') else 1)"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 20s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    
    # Labels for organization
    labels:
      - "com.entrospies.service=telegram-bot"
      - "com.entrospies.version=1.0"
      - "com.entrospies.description=EntroSpies Telegram Infostealer Bot"

# Network configuration
networks:
  entrospies-network:
    driver: bridge
    name: entrospies-network